import 'package:flutter/material.dart';
const topBackgroundGradient = Color(0xFF5C577C);
const botBackgroundGradient = Color(0xFF2A2837);
const primarySwatch = Colors.grey;
const primaryColor = Colors.black;
const brightness = Brightness.dark;
const accentColor = Colors.white;
const accentIconTheme = IconThemeData(color: Colors.black);
const dividerColor = Colors.black;
const calendarBackground = Colors.black;
const calendarText = Colors.white;
const calendarChevron = topBackgroundGradient;